export const BOARD_HEIGHT = 7;
export const BOARD_WIDTH = 7;

export const APP_WIDTH_PX = 600;
export const APP_HEIGHT_PX = 1000;

export const BOARD_PADDING_PX = 20;
export const BOARD_SIZE = APP_WIDTH_PX - BOARD_PADDING_PX * 2;
export const BOARD_POSITION_X = BOARD_PADDING_PX;
export const BOARD_POSITION_Y = APP_HEIGHT_PX - BOARD_SIZE - BOARD_PADDING_PX;

export const PANEL_SIZE_X = BOARD_SIZE;
export const PANEL_SIZE_Y = APP_HEIGHT_PX - BOARD_SIZE - BOARD_PADDING_PX * 3;
export const PANEL_POSITION_X = BOARD_PADDING_PX;
export const PANEL_POSITION_Y = BOARD_PADDING_PX;

export const TILE_SIZE = BOARD_SIZE / BOARD_WIDTH;

export const MODAL_WIDTH = 500;
export const MODAL_HEIGHT = 800;